language: cpp
compiler:
  - clang
  - gcc
install:
  - wget http://www.biicode.com/downloads/latest/ubuntu64 -O bii-ubuntu64.deb
  - sudo dpkg -i bii-ubuntu64.deb && sudo apt-get -f install
  - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
  - sudo tar -xzf cmake-3.0.2-Linux-64.tar.gz --strip 1 -C /usr
script:
  - cd /tmp
  - bii init boost-nowide
  - cd boost-nowide
  - bii new MikaelSmith/boost-nowide
  - shopt -s dotglob && mv $TRAVIS_BUILD_DIR/* blocks/MikaelSmith/boost-nowide
  - bii cpp:build -- -j2
  - cd build
  - ctest -V 2>&1 | c++filt
os:
  - linux
