version: 1.0.{build}
skip_tags: true
clone_folder: c:\projects\boost-nowide
os: unstable
environment:
  BOOST_ROOT: c:\Libraries\boost
  block_user: MikaelSmith
  block_name: boost-nowide
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
install:
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - bii-win.exe /VERYSILENT
  - set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
before_build:
  - if "%PLATFORM%" == "Win32" set CMAKE_GENERATOR="Visual Studio 12"
  - if "%PLATFORM%" == "x64"   set CMAKE_GENERATOR="Visual Studio 12 Win64"
  - cd \
  - bii init boost-nowide
  - cd boost-nowide
  - bii new %block_user%/%block_name%
  - xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\%block_user%\%block_name%\ /e
  - bii cpp:configure -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%Configuration%
build_script:
  - bii cpp:build
test_script:
  - cd \boost-nowide\build && ctest -C %Configuration%
